#!/bin/bash

# Installs/configures the packages used in all images
# and creates the pootle user

set -e


apt-get update -qq
apt-get install \
   -y \
   -qq \
   --no-install-recommends \
   --no-install-suggests \
   gnupg2 \
   gosu \
   locales \
   software-properties-common \
   virtualenv \
   wget

if [ ! -z "$GPG_KEYS" ]; then
    for key in $GPG_KEYS; do
	key=$(echo "$key" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
	echo "Adding GPG key: $key"
	wget -qO - $key | apt-key add -
    done <<< "$keys"
fi

if [ ! -z "$DEB_REPOS" ]; then
    export IFS=";"
    for repo in $DEB_REPOS; do
	repo=$(echo "$repo" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
	echo "Adding Debian repository: $repo"
	apt-add-repository "$repo"
    done
fi

pkgs=$(echo "$SYSTEM_PKGS" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
apt update
apt dist-upgrade -y -qq
apt install \
   -y \
   -qq \
   --no-install-recommends \
   --no-install-suggests \
   "$pkgs"

rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
apt-get clean
if cat /etc/locale.gen | grep "en_US.UTF-8 UTF-8" | grep -v "^\#"; then
    echo "Locale already set"
else
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen
fi
update-locale LANG=$LOCALE

if id "$APP_USERNAME" > /dev/null 2>&1; then
    echo "User already exists: $APP_USERNAME"
else
    useradd \
	-m \
	-u $APP_USER_ID \
	-d /home/$APP_USERNAME \
	-k /etc/skel \
	-s /bin/bash \
	$APP_USERNAME
fi
echo "creating app dir: $APP_DIR"
mkdir -p "$APP_DIR"
chown -R $APP_USERNAME:$APP_USERNAME "$APP_DIR"
